package com.example.memorygame.game

import jakarta.persistence.*
import java.time.LocalDateTime

/**
 * Represents a completed memory game result stored in the database.
 *
 * Each [GameResult] records the board size, number of guesses,
 * completion time, and the username of the player.
 *
 * This entity is mapped to the "game_results" table in the H2 database.
 *
 * @property id Unique identifier for the game result (auto-generated).
 * @property rows Number of rows on the game board.
 * @property cols Number of columns on the game board.
 * @property guesses Number of guesses taken to complete the game.
 * @property completedAt Timestamp when the game was completed.
 * @property username Name of the player who completed the game (defaults to "Anonymous").
 */
@Entity
@Table(name = "game_results")
data class GameResult(
    /** Primary key, automatically generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0,

    /** Number of rows on the board for this game */
    val rows: Int,

    /** Number of columns on the board for this game */
    val cols: Int,

    /** Number of guesses taken by the player to complete the game */
    val guesses: Int,

    /** Timestamp when the game was completed, defaults to current time */
    val completedAt: LocalDateTime = LocalDateTime.now(),

    /** Username of the player; defaults to "Anonymous" if not provided */
    var username: String = "Anonymous"
)